### ISSUE TITLE
Create Contact Us page 

### ISSUE THREAD

**Issue by Jis369** [VAbhijith2003github/SIH#12]
- [x] Take images of logo of govt of Jharkhand , our team pic and some other related pic. Convert these images to webp format and store it in images folder.
- [x] import these images to about us page 
- [x] make the page layout using css and bootstap ( it must be responsive)

![image](https://github.com/VAbhijith2003github/SIH/assets/109748693/dbb5134a-e50b-47c6-af39-618ecf2ae879)
@vish345

**Comment by georgioupanayiotis** [comment]
can you assign this to me @Jis369

**Comment by 08Uzair** [comment]
#12 Please assign this to me

**Comment by sakshipatil4403** [comment]
@VAbhijith2003github pls assign me this

**Comment by 08Uzair** [comment]
Please assign me i will complete this work in 1-2hrs

**Comment by Jis369** [comment]
Created Contact Us page along with  separate about.css
