### ISSUE TITLE
Create Login page

### ISSUE THREAD

**Issue by VAbhijith2003github** [VAbhijith2003github/SIH#21]
Create a login page with modern UI that diverts to register page if user wants to create account
![image](https://github.com/VAbhijith2003github/SIH/assets/119759593/5e9494d5-fe07-4fea-998a-2462b17e6930)

**Comment by Honey2339** [comment]
Interesting , i would like to work on this

**Comment by VAbhijith2003github** [comment]
fixed with the PR #22
